### ISSUE TITLE
✅ [2023.03.14] Carousel 공동 컴포넌트 제작 #12

### ISSUE THREAD

**Issue by kimzeze** [Lab20-Mosobamboo/Monstera#12]
## 작업 사항
swiper 라이브러리를 사용하여 carousel 공동 컴포넌트를 제작합니다.

## Todo
- [x] swiper 라이브러리 install
- [x] storybook과 충돌이 있는지 Test
- [x] carousel 공동 컴포넌트 jsx 파일 구성
- [x] carousel 기본 CSS 세팅
